"""Initial migration

Revision ID: a31a97fa8a01
Revises: 
Create Date: 2025-04-20 22:14:07.991897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31a97fa8a01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_symbol'), ['symbol'], unique=False)

    op.create_table('config_value',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('trade',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('closed_at_timestamp', sa.DateTime(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('tier', sa.String(length=10), nullable=True),
    sa.Column('calculated_fee', sa.Float(), nullable=True),
    sa.Column('volume_contribution', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_closed_at_timestamp'), ['closed_at_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_timestamp'), ['timestamp'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_timestamp'))
        batch_op.drop_index(batch_op.f('ix_trade_symbol'))
        batch_op.drop_index(batch_op.f('ix_trade_closed_at_timestamp'))

    op.drop_table('trade')
    op.drop_table('config_value')
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_symbol'))

    op.drop_table('balance')
    # ### end Alembic commands ###
